from fastapi import APIRouter
from pydantic import BaseModel
import asyncio

# Initialize the router
router = APIRouter()

# Define the exact JSON payload expected from the React frontend
class HealRequest(BaseModel):
    language: str
    error_message: str
    source_code: str

# Define the exact JSON response sent back to React
class HealResponse(BaseModel):
    explanation: str
    fixed_code: str

# Notice the endpoint is exactly "/heal-code" to match your fetch request
@router.post("/heal-code", response_model=HealResponse)
async def heal_broken_code(request: HealRequest):
    # Simulate the time it takes for an LLM to scan and repair the code
    await asyncio.sleep(2.5)
    
    # Mock explanation of what the AI "did"
    mock_explanation = (
        f"MOCK AI: Analyzed {request.language} code. "
        f"Detected syntax anomalies based on the prompt: '{request.error_message}'. "
        f"Replaced brittle logic with resilient patterns and flushed the execution context."
    )
    
    # Mock healed code output
    mock_fixed_code = f"""# Healed {request.language.capitalize()} Code
# Auto-generated by Guardian V2 Local Engine

def reliable_execution_block():
    try:
        # Replaced unstable selectors/syntax with type-safe operations
        status = execute_safely()
        return True
    except Exception as e:
        log_error(e)
        return False
"""

    # Return the exact JSON structure React is waiting for
    return HealResponse(
        explanation=mock_explanation,
        fixed_code=mock_fixed_code
    )